package kotlin.reflect.jvm.internal.impl.util;

import com.facebook.appevents.iap.InAppPurchaseConstants;
import java.util.Map;
import java.util.Set;
import kotlin.TuplesKt;
import kotlin.collections.MapsKt;
import kotlin.collections.SetsKt;
import kotlin.reflect.jvm.internal.impl.name.Name;
import kotlin.text.Regex;
import org.eclipse.paho.client.mqttv3.MqttTopic;

/* JADX INFO: loaded from: classes5.dex */
public final class OperatorNameConventions {
    public static final Set<Name> ALL_BINARY_OPERATION_NAMES;
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Set<Name> BITWISE_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final Regex COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HASH_CODE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INV;
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Set<Name> NUMBER_CONVERSIONS;
    public static final Name OF;
    public static final Name OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name RANGE_UNTIL;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Name SHL;
    public static final Name SHR;
    public static final Set<Name> SIMPLE_BINARY_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_BITWISE_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Set<Name> STATEMENT_LIKE_OPERATORS;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    private static final Map<Name, String> TOKENS_BY_OPERATOR_NAME;
    public static final Name TO_BYTE;
    public static final Name TO_CHAR;
    public static final Name TO_DOUBLE;
    public static final Name TO_FLOAT;
    public static final Name TO_INT;
    public static final Name TO_LONG;
    public static final Name TO_SHORT;
    public static final Name TO_STRING;
    public static final Name TO_UBYTE;
    public static final Name TO_UINT;
    public static final Name TO_ULONG;
    public static final Name TO_USHORT;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;
    public static final Set<Name> UNSIGNED_CONVERSIONS;
    public static final Name USHR;
    public static final Name XOR;

    static {
        Name nameIdentifier = Name.identifier("getValue");
        nameIdentifier.getClass();
        GET_VALUE = nameIdentifier;
        Name nameIdentifier2 = Name.identifier("setValue");
        nameIdentifier2.getClass();
        SET_VALUE = nameIdentifier2;
        Name nameIdentifier3 = Name.identifier("provideDelegate");
        nameIdentifier3.getClass();
        PROVIDE_DELEGATE = nameIdentifier3;
        Name nameIdentifier4 = Name.identifier("equals");
        nameIdentifier4.getClass();
        EQUALS = nameIdentifier4;
        Name nameIdentifier5 = Name.identifier("hashCode");
        nameIdentifier5.getClass();
        HASH_CODE = nameIdentifier5;
        Name nameIdentifier6 = Name.identifier("compareTo");
        nameIdentifier6.getClass();
        COMPARE_TO = nameIdentifier6;
        Name nameIdentifier7 = Name.identifier("contains");
        nameIdentifier7.getClass();
        CONTAINS = nameIdentifier7;
        Name nameIdentifier8 = Name.identifier("invoke");
        nameIdentifier8.getClass();
        INVOKE = nameIdentifier8;
        Name nameIdentifier9 = Name.identifier("iterator");
        nameIdentifier9.getClass();
        ITERATOR = nameIdentifier9;
        Name nameIdentifier10 = Name.identifier("get");
        nameIdentifier10.getClass();
        GET = nameIdentifier10;
        Name nameIdentifier11 = Name.identifier("set");
        nameIdentifier11.getClass();
        SET = nameIdentifier11;
        Name nameIdentifier12 = Name.identifier("next");
        nameIdentifier12.getClass();
        NEXT = nameIdentifier12;
        Name nameIdentifier13 = Name.identifier("hasNext");
        nameIdentifier13.getClass();
        HAS_NEXT = nameIdentifier13;
        Name nameIdentifier14 = Name.identifier("of");
        nameIdentifier14.getClass();
        OF = nameIdentifier14;
        Name nameIdentifier15 = Name.identifier(InAppPurchaseConstants.METHOD_TO_STRING);
        nameIdentifier15.getClass();
        TO_STRING = nameIdentifier15;
        COMPONENT_REGEX = new Regex("component\\d+");
        Name nameIdentifier16 = Name.identifier("and");
        nameIdentifier16.getClass();
        AND = nameIdentifier16;
        Name nameIdentifier17 = Name.identifier("or");
        nameIdentifier17.getClass();
        OR = nameIdentifier17;
        Name nameIdentifier18 = Name.identifier("xor");
        nameIdentifier18.getClass();
        XOR = nameIdentifier18;
        Name nameIdentifier19 = Name.identifier("inv");
        nameIdentifier19.getClass();
        INV = nameIdentifier19;
        Name nameIdentifier20 = Name.identifier("shl");
        nameIdentifier20.getClass();
        SHL = nameIdentifier20;
        Name nameIdentifier21 = Name.identifier("shr");
        nameIdentifier21.getClass();
        SHR = nameIdentifier21;
        Name nameIdentifier22 = Name.identifier("ushr");
        nameIdentifier22.getClass();
        USHR = nameIdentifier22;
        Name nameIdentifier23 = Name.identifier("inc");
        nameIdentifier23.getClass();
        INC = nameIdentifier23;
        Name nameIdentifier24 = Name.identifier("dec");
        nameIdentifier24.getClass();
        DEC = nameIdentifier24;
        Name nameIdentifier25 = Name.identifier("plus");
        nameIdentifier25.getClass();
        PLUS = nameIdentifier25;
        Name nameIdentifier26 = Name.identifier("minus");
        nameIdentifier26.getClass();
        MINUS = nameIdentifier26;
        Name nameIdentifier27 = Name.identifier("not");
        nameIdentifier27.getClass();
        NOT = nameIdentifier27;
        Name nameIdentifier28 = Name.identifier("unaryMinus");
        nameIdentifier28.getClass();
        UNARY_MINUS = nameIdentifier28;
        Name nameIdentifier29 = Name.identifier("unaryPlus");
        nameIdentifier29.getClass();
        UNARY_PLUS = nameIdentifier29;
        Name nameIdentifier30 = Name.identifier("times");
        nameIdentifier30.getClass();
        TIMES = nameIdentifier30;
        Name nameIdentifier31 = Name.identifier("div");
        nameIdentifier31.getClass();
        DIV = nameIdentifier31;
        Name nameIdentifier32 = Name.identifier("rem");
        nameIdentifier32.getClass();
        REM = nameIdentifier32;
        Name nameIdentifier33 = Name.identifier("rangeTo");
        nameIdentifier33.getClass();
        RANGE_TO = nameIdentifier33;
        Name nameIdentifier34 = Name.identifier("rangeUntil");
        nameIdentifier34.getClass();
        RANGE_UNTIL = nameIdentifier34;
        Name nameIdentifier35 = Name.identifier("timesAssign");
        nameIdentifier35.getClass();
        TIMES_ASSIGN = nameIdentifier35;
        Name nameIdentifier36 = Name.identifier("divAssign");
        nameIdentifier36.getClass();
        DIV_ASSIGN = nameIdentifier36;
        Name nameIdentifier37 = Name.identifier("remAssign");
        nameIdentifier37.getClass();
        REM_ASSIGN = nameIdentifier37;
        Name nameIdentifier38 = Name.identifier("plusAssign");
        nameIdentifier38.getClass();
        PLUS_ASSIGN = nameIdentifier38;
        Name nameIdentifier39 = Name.identifier("minusAssign");
        nameIdentifier39.getClass();
        MINUS_ASSIGN = nameIdentifier39;
        Name nameIdentifier40 = Name.identifier("toDouble");
        nameIdentifier40.getClass();
        TO_DOUBLE = nameIdentifier40;
        Name nameIdentifier41 = Name.identifier("toFloat");
        nameIdentifier41.getClass();
        TO_FLOAT = nameIdentifier41;
        Name nameIdentifier42 = Name.identifier("toLong");
        nameIdentifier42.getClass();
        TO_LONG = nameIdentifier42;
        Name nameIdentifier43 = Name.identifier("toInt");
        nameIdentifier43.getClass();
        TO_INT = nameIdentifier43;
        Name nameIdentifier44 = Name.identifier("toChar");
        nameIdentifier44.getClass();
        TO_CHAR = nameIdentifier44;
        Name nameIdentifier45 = Name.identifier("toShort");
        nameIdentifier45.getClass();
        TO_SHORT = nameIdentifier45;
        Name nameIdentifier46 = Name.identifier("toByte");
        nameIdentifier46.getClass();
        TO_BYTE = nameIdentifier46;
        Name nameIdentifier47 = Name.identifier("toULong");
        nameIdentifier47.getClass();
        TO_ULONG = nameIdentifier47;
        Name nameIdentifier48 = Name.identifier("toUInt");
        nameIdentifier48.getClass();
        TO_UINT = nameIdentifier48;
        Name nameIdentifier49 = Name.identifier("toUShort");
        nameIdentifier49.getClass();
        TO_USHORT = nameIdentifier49;
        Name nameIdentifier50 = Name.identifier("toUByte");
        nameIdentifier50.getClass();
        TO_UBYTE = nameIdentifier50;
        UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier23, nameIdentifier24, nameIdentifier29, nameIdentifier28, nameIdentifier27, nameIdentifier19});
        SIMPLE_UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier29, nameIdentifier28, nameIdentifier27, nameIdentifier19});
        Set<Name> of = SetsKt.setOf((Object[]) new Name[]{nameIdentifier30, nameIdentifier25, nameIdentifier26, nameIdentifier31, nameIdentifier32, nameIdentifier33, nameIdentifier34});
        BINARY_OPERATION_NAMES = of;
        SIMPLE_BINARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier30, nameIdentifier25, nameIdentifier26, nameIdentifier31, nameIdentifier32});
        Set<Name> of2 = SetsKt.setOf((Object[]) new Name[]{nameIdentifier16, nameIdentifier17, nameIdentifier18, nameIdentifier19, nameIdentifier20, nameIdentifier21, nameIdentifier22});
        BITWISE_OPERATION_NAMES = of2;
        SIMPLE_BITWISE_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier16, nameIdentifier17, nameIdentifier18, nameIdentifier20, nameIdentifier21, nameIdentifier22});
        ALL_BINARY_OPERATION_NAMES = SetsKt.plus(SetsKt.plus((Set) of, (Iterable) of2), (Iterable) SetsKt.setOf((Object[]) new Name[]{nameIdentifier4, nameIdentifier7, nameIdentifier6}));
        Set<Name> of3 = SetsKt.setOf((Object[]) new Name[]{nameIdentifier35, nameIdentifier36, nameIdentifier37, nameIdentifier38, nameIdentifier39});
        ASSIGNMENT_OPERATIONS = of3;
        DELEGATED_PROPERTY_OPERATORS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier, nameIdentifier2, nameIdentifier3});
        STATEMENT_LIKE_OPERATORS = SetsKt.plus(SetsKt.setOf(nameIdentifier11), (Iterable) of3);
        NUMBER_CONVERSIONS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier40, nameIdentifier41, nameIdentifier42, nameIdentifier43, nameIdentifier45, nameIdentifier46, nameIdentifier44});
        UNSIGNED_CONVERSIONS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier47, nameIdentifier48, nameIdentifier49, nameIdentifier50});
        TOKENS_BY_OPERATOR_NAME = MapsKt.mapOf(TuplesKt.to(nameIdentifier23, "++"), TuplesKt.to(nameIdentifier24, "--"), TuplesKt.to(nameIdentifier29, MqttTopic.SINGLE_LEVEL_WILDCARD), TuplesKt.to(nameIdentifier28, "-"), TuplesKt.to(nameIdentifier27, "!"), TuplesKt.to(nameIdentifier30, "*"), TuplesKt.to(nameIdentifier25, MqttTopic.SINGLE_LEVEL_WILDCARD), TuplesKt.to(nameIdentifier26, "-"), TuplesKt.to(nameIdentifier31, MqttTopic.TOPIC_LEVEL_SEPARATOR), TuplesKt.to(nameIdentifier32, "%"), TuplesKt.to(nameIdentifier33, ".."), TuplesKt.to(nameIdentifier34, "..<"));
    }

    private OperatorNameConventions() {
    }
}
