package com.google.android.gms.internal.ads;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import java.util.Map;

/* JADX INFO: loaded from: classes3.dex */
final class zzgdv implements zzggy {
    private final zzgdl zzA;
    private final zzgdr zzB;
    final zzind zza;
    final zzind zzb;
    final zzind zzc;
    final zzind zzd;
    final zzind zze;
    final zzind zzf;
    final zzind zzg;
    final zzind zzh;
    final zzind zzi;
    final zzind zzj;
    final zzind zzk;
    final zzind zzl;
    final zzind zzm;
    final zzind zzn;
    final zzind zzo;
    final zzind zzp;
    final zzind zzq;
    final zzind zzr;
    final zzind zzs;
    final zzind zzt;
    final zzind zzu;
    final zzind zzv;
    final zzind zzw;
    final zzind zzx;
    final zzind zzy;
    final zzind zzz;

    public zzgdv(zzgdl zzgdlVar, zzgdr zzgdrVar, Context context, View view, Activity activity, String str, Map map, zzaxm zzaxmVar, zzgec zzgecVar) {
        this.zzA = zzgdlVar;
        this.zzB = zzgdrVar;
        zzimu zzimuVarZza = zzimv.zza(zzgecVar);
        this.zza = zzimuVarZza;
        zzimu zzimuVarZzc = zzimv.zzc(str);
        this.zzb = zzimuVarZzc;
        zzimu zzimuVarZza2 = zzimv.zza(zzaxmVar);
        this.zzc = zzimuVarZza2;
        zzind zzindVar = zzgdrVar.zzb;
        zzind zzindVar2 = zzgdlVar.zza;
        zzind zzindVar3 = zzgdlVar.zzu;
        zzgij zzgijVarZza = zzgij.zza(zzimuVarZza2, zzindVar, zzindVar2, zzindVar3);
        this.zzd = zzgijVarZza;
        zzgih zzgihVarZza = zzgih.zza(zzimuVarZza2, zzindVar, zzindVar3);
        this.zze = zzgihVarZza;
        zzimu zzimuVarZza3 = zzimv.zza(map);
        this.zzf = zzimuVarZza3;
        zzind zzindVar4 = zzgdrVar.zzb;
        zzind zzindVar5 = zzgdlVar.zzu;
        zzgip zzgipVarZza = zzgip.zza(zzimuVarZza2, zzindVar4, zzimuVarZza3, zzindVar5);
        this.zzg = zzgipVarZza;
        zzgil zzgilVarZza = zzgil.zza(zzimuVarZza2, zzindVar4, zzgdlVar.zzj, zzindVar5);
        this.zzh = zzgilVarZza;
        zzgiz zzgizVarZza = zzgiz.zza(zzimuVarZza2, zzindVar4, zzimuVarZza, zzimuVarZza3, zzindVar5);
        this.zzi = zzgizVarZza;
        zzgin zzginVarZza = zzgin.zza(zzimuVarZza2, zzindVar4, zzindVar5);
        this.zzj = zzginVarZza;
        zzimu zzimuVarZza4 = zzimv.zza(context);
        this.zzk = zzimuVarZza4;
        zzind zzindVar6 = zzgdrVar.zzb;
        zzind zzindVar7 = zzgdlVar.zzu;
        zzgiv zzgivVarZza = zzgiv.zza(zzimuVarZza2, zzindVar6, zzimuVarZza, zzimuVarZza4, zzimuVarZza3, zzindVar7);
        this.zzl = zzgivVarZza;
        zzind zzindVar8 = zzgdlVar.zza;
        zzind zzindVar9 = zzgdlVar.zzj;
        zzgif zzgifVarZza = zzgif.zza(zzimuVarZza2, zzindVar6, zzimuVarZza3, zzindVar8, zzimuVarZza, zzindVar9, zzindVar7);
        this.zzm = zzgifVarZza;
        zzgir zzgirVarZza = zzgir.zza(zzimuVarZza2, zzindVar6, zzindVar8, zzindVar7);
        this.zzn = zzgirVarZza;
        zzgit zzgitVarZza = zzgit.zza(zzimuVarZza2, zzindVar6, zzimuVarZza3, zzindVar8, zzindVar7);
        this.zzo = zzgitVarZza;
        zzgid zzgidVarZza = zzgid.zza(zzimuVarZza2, zzimuVarZza3, zzindVar9, zzindVar7);
        this.zzp = zzgidVarZza;
        zzinf zzinfVarZza = zzing.zza(11, 0);
        zzinfVarZza.zza(zzgijVarZza);
        zzinfVarZza.zza(zzgihVarZza);
        zzinfVarZza.zza(zzgipVarZza);
        zzinfVarZza.zza(zzgilVarZza);
        zzinfVarZza.zza(zzgizVarZza);
        zzinfVarZza.zza(zzginVarZza);
        zzinfVarZza.zza(zzgivVarZza);
        zzinfVarZza.zza(zzgifVarZza);
        zzinfVarZza.zza(zzgirVarZza);
        zzinfVarZza.zza(zzgitVarZza);
        zzinfVarZza.zza(zzgidVarZza);
        zzing zzingVarZzc = zzinfVarZza.zzc();
        this.zzq = zzingVarZzc;
        zzimu zzimuVarZzc2 = zzimv.zzc(view);
        this.zzr = zzimuVarZzc2;
        zzimu zzimuVarZzc3 = zzimv.zzc(activity);
        this.zzs = zzimuVarZzc3;
        zzind zzindVar10 = zzgdrVar.zzb;
        zzind zzindVar11 = zzgdlVar.zzu;
        zzgib zzgibVarZza = zzgib.zza(zzimuVarZza2, zzindVar10, zzimuVarZzc2, zzimuVarZzc3, zzindVar11);
        this.zzt = zzgibVarZza;
        zzind zzindVarZza = zzimt.zza(zzggz.zza(zzimuVarZza4));
        this.zzu = zzindVarZza;
        zzgjd zzgjdVarZza = zzgjd.zza(zzimuVarZza2, zzindVar10, zzindVarZza, zzimuVarZzc2, zzindVar11);
        this.zzv = zzgjdVarZza;
        zzinf zzinfVarZza2 = zzing.zza(11, 0);
        zzinfVarZza2.zza(zzgijVarZza);
        zzinfVarZza2.zza(zzgihVarZza);
        zzinfVarZza2.zza(zzgilVarZza);
        zzinfVarZza2.zza(zzgibVarZza);
        zzinfVarZza2.zza(zzgjdVarZza);
        zzinfVarZza2.zza(zzgizVarZza);
        zzinfVarZza2.zza(zzginVarZza);
        zzinfVarZza2.zza(zzgivVarZza);
        zzinfVarZza2.zza(zzgifVarZza);
        zzinfVarZza2.zza(zzgirVarZza);
        zzinfVarZza2.zza(zzgitVarZza);
        zzing zzingVarZzc2 = zzinfVarZza2.zzc();
        this.zzw = zzingVarZzc2;
        zzgjb zzgjbVarZza = zzgjb.zza(zzimuVarZza2, zzgdrVar.zzb, zzimuVarZza3, zzindVarZza, zzgdlVar.zzu);
        this.zzx = zzgjbVarZza;
        zzinf zzinfVarZza3 = zzing.zza(12, 0);
        zzinfVarZza3.zza(zzgijVarZza);
        zzinfVarZza3.zza(zzgihVarZza);
        zzinfVarZza3.zza(zzgilVarZza);
        zzinfVarZza3.zza(zzgibVarZza);
        zzinfVarZza3.zza(zzgjdVarZza);
        zzinfVarZza3.zza(zzgizVarZza);
        zzinfVarZza3.zza(zzginVarZza);
        zzinfVarZza3.zza(zzgivVarZza);
        zzinfVarZza3.zza(zzgifVarZza);
        zzinfVarZza3.zza(zzgirVarZza);
        zzinfVarZza3.zza(zzgitVarZza);
        zzinfVarZza3.zza(zzgjbVarZza);
        zzing zzingVarZzc3 = zzinfVarZza3.zzc();
        this.zzy = zzingVarZzc3;
        this.zzz = zzimt.zza(zzggw.zza(zzgdlVar.zzx, zzgdlVar.zzG, zzgdrVar.zzb, zzimuVarZza, zzimuVarZzc, zzimuVarZza2, zzingVarZzc, zzingVarZzc2, zzingVarZzc3, zzgdlVar.zzu));
    }

    @Override // com.google.android.gms.internal.ads.zzggy
    public final zzggv zza() {
        return (zzggv) this.zzz.zzb();
    }
}
