package com.google.android.gms.internal.ads;

/* JADX INFO: loaded from: classes3.dex */
enum zzgkn {
    RESULT_UNKNOWN,
    RESULT_NOOP_LOCAL_PROGRAM_STILL_VALID,
    RESULT_UPDATED,
    RESULT_NOOP_NO_NEW_PROGRAM,
    RESULT_FAILURE_INVALID_RESPONSE,
    RESULT_FAILURE_FETCHER_HTTP_RUNTIME_EXCEPTION
}
