package com.google.android.gms.wearable;

import com.google.android.gms.common.Feature;

/* JADX INFO: loaded from: classes3.dex */
public abstract class zzn {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature[] zzH;
    public static final Feature zza;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    static {
        Feature feature = new Feature("app_client", 4L, true);
        zza = feature;
        Feature feature2 = new Feature("carrier_auth", 1L, true);
        zzb = feature2;
        Feature feature3 = new Feature("wear3_oem_companion", 1L, true);
        zzc = feature3;
        Feature feature4 = new Feature("wear_await_data_sync_complete", 1L, true);
        zzd = feature4;
        Feature feature5 = new Feature("wear_backup_restore", 8L, true);
        zze = feature5;
        Feature feature6 = new Feature("wear_consent", 2L, true);
        zzf = feature6;
        Feature feature7 = new Feature("wear_consent_recordoptin", 1L, true);
        zzg = feature7;
        Feature feature8 = new Feature("wear_consent_recordoptin_swaadl", 1L, true);
        zzh = feature8;
        Feature feature9 = new Feature("wear_consent_supervised", 2L, true);
        zzi = feature9;
        Feature feature10 = new Feature("wear_get_phone_switching_feature_status", 1L, true);
        zzj = feature10;
        Feature feature11 = new Feature("wear_fast_pair_account_key_sync", 1L, true);
        zzk = feature11;
        Feature feature12 = new Feature("wear_fast_pair_get_account_keys", 1L, true);
        zzl = feature12;
        Feature feature13 = new Feature("wear_fast_pair_get_account_key_by_account", 1L, true);
        zzm = feature13;
        Feature feature14 = new Feature("wear_flush_batched_data", 1L, true);
        zzn = feature14;
        Feature feature15 = new Feature("wear_get_related_configs", 1L, true);
        zzo = feature15;
        Feature feature16 = new Feature("wear_get_node_id", 1L, true);
        zzp = feature16;
        Feature feature17 = new Feature("wear_logging_service", 2L, true);
        zzq = feature17;
        Feature feature18 = new Feature("wear_retry_connection", 1L, true);
        zzr = feature18;
        Feature feature19 = new Feature("wear_set_cloud_sync_setting_by_node", 1L, true);
        zzs = feature19;
        Feature feature20 = new Feature("wear_first_party_consents", 2L, true);
        zzt = feature20;
        Feature feature21 = new Feature("wear_update_config", 1L, true);
        zzu = feature21;
        Feature feature22 = new Feature("wear_update_connection_retry_strategy", 1L, true);
        zzv = feature22;
        Feature feature23 = new Feature("wear_update_delay_config", 1L, true);
        zzw = feature23;
        Feature feature24 = new Feature("wearable_services", 1L, true);
        zzx = feature24;
        Feature feature25 = new Feature("wear_cancel_migration", 1L, true);
        zzy = feature25;
        Feature feature26 = new Feature("wear_customizable_screens", 2L, true);
        zzz = feature26;
        Feature feature27 = new Feature("wear_wifi_immediate_connect", 1L, true);
        zzA = feature27;
        Feature feature28 = new Feature("wear_get_node_active_network_metered", 1L, true);
        zzB = feature28;
        Feature feature29 = new Feature("wear_consents_per_watch", 3L, true);
        zzC = feature29;
        Feature feature30 = new Feature("wear_material3_experience", 1L, true);
        zzD = feature30;
        Feature feature31 = new Feature("wear_offload_connection", 1L, true);
        zzE = feature31;
        Feature feature32 = new Feature("wear_get_local_capabilities", 1L, true);
        zzF = feature32;
        Feature feature33 = new Feature("wear_notify_channel_flushed", 1L, true);
        zzG = feature33;
        zzH = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, feature15, feature16, feature17, feature18, feature19, feature20, feature21, feature22, feature23, feature24, feature25, feature26, feature27, feature28, feature29, feature30, feature31, feature32, feature33};
    }
}
